######################## default configuration ####################
baseURL = "http://websitewithtabs.netlify.com/"
title = "Bigspring Hugo"
theme = "bigspring"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "" # example : UA-123-45
# unsafe html
[markup.goldmark.renderer]
unsafe = true

#slate config
[ params ]
BackgroundImages = ["bg/1.jpg", "bg/2.jpg", "bg/3.jpg", "bg/4.jpg", "bg/5.jpg"]
Favicon = "favicon.ico"
BackgroundStyle = "#657383"
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "Python Basics"
tag = "python"
icon = "code"

[[ params.nav ]]
name = "Data Science"
tag = "data"
icon = "database"

[[ params.nav ]]
name = "AI"
tag = "ai"
icon = "braille"

[[ params.nav ]]
name = "3D Printing"
tag = "cad"
icon = "cube"

[[ params.nav ]]
name = "VR"
tag = "vr"
icon = "eye"

[[ params.nav ]]
name = "AR"
tag = "ar"
icon = "cubes"

[[ params.nav ]]
name = "Web Design"
tag = "web"
icon = "laptop"

[[ params.nav ]]
name = "App Design"
tag = "app"
icon = "mobile"

[[ params.nav ]]
name = "Embedded Systems"
tag = "embedded"
icon = "microchip"