[build]
publish = "public"
command = """hugo \
  --source \
  --config config/_default/config.toml \
  --themesDir ../.. \
  --theme repo \
  --baseURL http://websitewithtabs.netlify.com/"""

[build.environment]
HUGO_VERSION = "0.74.3"
HUGO_THEME = "repo"
HUGO_BASEURL = "/"
