on:
  schedule:
    - cron: '30 21 * * *'

name: Check markdown links
jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v1
        with:
          url: https://websitewithtabs.netlify.app/
