on:
  schedule:
    - cron: '0 0 * * *'

name: Check markdown links
jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v1.0.3

        with:
          url: https://websitewithtabs.netlify.app/
          cmd_params: --exclude=https://websitewithtabs.netlify.app/courses/
