on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

name: Check markdown links
jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v1.0.3

        with:
          url: https://websitewithtabs.netlify.app/
          cmd_params: --exclude=https://use.fontawesome.com 
                      --exclude=https://fonts.gstatic.com  --exclude=https://gethugothemes.com/ 
                      --exclude=^//www.*$
                      --exclude=(https?:)?//platform.twitter.com
                      --exclude=(https?:)?//fonts.googleapis.com
                      --exclude=(https?:)?//platform.linkedin.com
                      --exclude=//websitewithtabs.netlify.app/courses/#ai
                      --exclude=//websitewithtabs.netlify.app/courses/#app
                      --exclude=//websitewithtabs.netlify.app/courses/#ar
                      --exclude=//websitewithtabs.netlify.app/courses/#cad
                      --exclude=//websitewithtabs.netlify.app/courses/#data
                      --exclude=//websitewithtabs.netlify.app/courses/#embedded
                      --exclude=//websitewithtabs.netlify.app/courses/#python
                      --exclude=//websitewithtabs.netlify.app/courses/#vr
                      --exclude=//websitewithtabs.netlify.app/courses/#web
