on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

name: Check markdown links
jobs:
  my-broken-link-checker:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: ruzickap/action-my-broken-link-checker@v1.0.3

        with:
          url: https://websitewithtabs.netlify.app/
          cmd_params: --exclude=https://www.googletagmanager.com --exclude=https://platform.twitter.com --exclude=https://use.fontawesome.com --exclude=https://fonts.googleapis.com 
                      --exclude=https://fonts.gstatic.com  --exclude=https://gethugothemes.com/ --exclude=https://platform.linkedin.com --exclude=https://websitewithtabs.netlify.app/courses/#ai 
                      --exclude=https://websitewithtabs.netlify.app/courses/#app --exclude=https://websitewithtabs.netlify.app/courses/#ar --exclude=https://websitewithtabs.netlify.app/courses/#cad 
                      --exclude=https://websitewithtabs.netlify.app/courses/#data --exclude=https://websitewithtabs.netlify.app/courses/#embedded --exclude=https://websitewithtabs.netlify.app/courses/#python
                      --exclude=https://websitewithtabs.netlify.app/courses/#vr --exclude=https://websitewithtabs.netlify.app/courses/#web
