name: Action Hugo
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Hugo Broken Link Check
      uses: marccampbell/hugo-linkcheck-action@v0.1.3
    - name: Cypress run
      uses: cypress-io/github-action@v2
